### ISSUE TITLE
Chinese (Simplified) version

### ISSUE THREAD

**Issue by LogCreative** [DEViantUA/StarRailCard#1]
I discovered that the language setting `chs` or `zh` does not work on translation.
From [mihomo](https://github.com/KT-Yeh/mihomo/blob/5a8d22f360c5d32a5ce7054a42999d32905a351d/mihomo/client.py#L14) repo, I found that only `cn` language identifier is available for Chinese (Simplified).

I replaced two places:

https://github.com/DEViantUA/StarRailCard/blob/3887db26d23366ec8a82429c4c9bb51eaeb43c27/starrailcard/src/tools/translation.py#L10

https://github.com/DEViantUA/StarRailCard/blob/3887db26d23366ec8a82429c4c9bb51eaeb43c27/starrailcard/src/tools/translation.py#L27

and get the following result:
![罗刹_29_07_2023 06_25](https://github.com/DEViantUA/StarRailCard/assets/61653082/24690e27-dd2a-4091-8a88-f37e4b938d0c)

As is shown, some characters are missing. I discovered that you are using font

https://github.com/DEViantUA/StarRailCard/blob/3887db26d23366ec8a82429c4c9bb51eaeb43c27/starrailcard/src/tools/openFile.py#L9
which is a Korean specified version of Noto Sans. I change the font to the font installed on my computer:
```
font = 'NotoSansCJKsc-Bold.otf'
```
which is a Chinese (Simplified) specified version. This will render a proper result:
![罗刹_29_07_2023 07_23](https://github.com/DEViantUA/StarRailCard/assets/61653082/575ce97d-4b33-439f-b45e-3e8e897f8612)

Unfortunately, there is no single file font for Noto Sans of all languages, see https://github.com/notofonts/noto-cjk/releases. I think an option to change the font may work.

**Comment by DEViantUA** [comment]
Thank you for your feedback, I'll add font support: ``NotoSansKR-Bold.otf`` In the next update, for this language.

**Comment by DEViantUA** [comment]
Fixed in version 0.0.8: https://pypi.org/project/starrailcard/#description

**Comment by LogCreative** [comment]
Probably there should also be an `openFile.change_font` in `get_profile`:
https://github.com/DEViantUA/StarRailCard/blob/65935e13e9f6528a14aca04810ef92d7543219cf/starrailcard/honkaicard.py#L149-L150

![profile](https://github.com/DEViantUA/StarRailCard/assets/61653082/91f4ba64-8732-4767-8e1d-f475dc04ed46)

**Comment by DEViantUA** [comment]
> Probably there should also be an `openFile.change_font` in `get_profile`:
> 
> https://github.com/DEViantUA/StarRailCard/blob/65935e13e9f6528a14aca04810ef92d7543219cf/starrailcard/honkaicard.py#L149-L150
> 
> ![profile](https://user-images.githubusercontent.com/61653082/277207326-91f4ba64-8732-4767-8e1d-f475dc04ed46.jpg)

Try now: https://github.com/DEViantUA/StarRailCard/releases/tag/new_version_1_2_0

**Comment by LogCreative** [comment]
I have installed the font globally and pass the option `font` manually to the object now. You are safe to remove `NotoCJKsc-Bold.otf` in your repo and your code to reduce some package size :)

**Comment by DEViantUA** [comment]
> I have installed the font globally and pass the option `font` manually to the object now. You are safe to remove `NotoCJKsc-Bold.otf` in your repo and your code to reduce some package size :)

Yes, you're right, this will all be fixed soon, yesterday just made a wireframe for new features
