### ISSUE TITLE
Image fixing for diffrent characters

### ISSUE THREAD

**Issue by ShresthVaibhav** [DEViantUA/StarRailCard#2]
![gg](https://github.com/DEViantUA/StarRailCard/assets/105759853/4e05992d-5a0a-4e99-b55c-a3e9a8a91757)

and while sending on telegram the text outside of format isnt visible cause its white

**Comment by DEViantUA** [comment]
Not visible on a white theme or a dark one?

**Comment by ShresthVaibhav** [comment]
> Not visible on a white theme or a dark one?

![image](https://github.com/DEViantUA/StarRailCard/assets/105759853/4c1ecfd1-62f7-4c44-8fb5-cae78e9e0053)

All of em

**Comment by DEViantUA** [comment]
Oh.. This problem is related to your way of uploading an image to telegram. 
Telegram supports png format, but in your screenshot, the card is converted to jpg format.

**Comment by DEViantUA** [comment]
![IMG_20230807_125719](https://github.com/DEViantUA/StarRailCard/assets/112615715/ee0e9cdf-38c5-420c-b131-cced75bfcd4b)

**Comment by ShresthVaibhav** [comment]
> Oh.. This problem is related to your way of uploading an image to telegram. Telegram supports png format, but in your screenshot, the card is converted to jpg format.


ok thanks for telling and what about splash art issue (of blade)?

**Comment by DEViantUA** [comment]
I can fix it, but it will only be an extra check and I will need to store the image somewhere.
