### ISSUE TITLE
ValidationError

### ISSUE THREAD

**Issue by K0cTu4eK** [DEViantUA/StarRailCard#5]
![Снимок экрана 2024-01-17 002120](https://github.com/DEViantUA/StarRailCard/assets/98667549/a8629ee2-6075-420b-9875-2a01c8bd23e1)
This problem appeared just a couple of weeks ago, possibly due to the pydantic 2.5 update. So, how do I fix it or what versions of the pydantic and pydantic_core libraries do you have?

**Comment by DEViantUA** [comment]
pip3.12 uninstall pydantic
pip3.12 install pydantic==1.10.13

**Comment by K0cTu4eK** [comment]
Thanks!
