### ISSUE TITLE
Validation errors for StarRailApiDataV2

### ISSUE THREAD

**Issue by DaniS001** [DEViantUA/StarRailCard#6]
Hi,
I wanted to run your code, but I get the following error.

<img width="868" alt="image" src="https://github.com/DEViantUA/StarRailCard/assets/40502581/552ad7e5-191b-4586-9143-9f2d9db618c7">

**Comment by DEViantUA** [comment]
![image](https://github.com/DEViantUA/StarRailCard/assets/112615715/b8aaf3d8-46da-42e1-8a2d-8bdd8f9b6c3c)

Install the normal version of pydantic

```
pip install pydantic==1.10.14
```

**Comment by DaniS001** [comment]
It works now. Thanks
