### ISSUE TITLE
Include all transitive dependencies when installing the module through PIP

### ISSUE THREAD

**Issue by Iqrar99** [DEViantUA/StarRailCard#8]
In an isolated env, when we run `pip install starrailcard`. It still didn't include all other necessary dependencies such as: `aiohttp`, `numpy`, `more_itertools`, `cachetools`, `bs4`, and such.

We were forced to pip them manually. It'll be good if you can include it on `setup.py` all required libs as well to make people more straightforward to use the module. Currently, only Pillow that is downloaded automatically.

**Comment by DEViantUA** [comment]
Module like base64 is a built-in module in Python. Its absence means that you installed Python by checking the box in the wrong place. In the new version I will add all additional modules but those that are standard will not be included

**Comment by Iqrar99** [comment]
Well, thank you, but I was referring to `bs4` as `beautifulsoup4`
